---
- name: Update system packages # Play to update the system packages
  hosts: all
  become: yes  # To run tasks with sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    # - name: Upgrade all packages
    #   apt:
    #     upgrade: dist
    #     update_cache: yes


- name: Install Apache HTTP Server # Play to install Apache HTTP Server
  hosts: all
  become: true

  tasks:
    - name: Install Apache HTTP Server
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

- name: Install containerd  # Play to install containerd directrly from github release
  hosts: all
  become: true

  tasks:
    - name: Download containerd archive
      become: true
      ansible.builtin.get_url:
        url: https://github.com/containerd/containerd/releases/download/v1.7.8/containerd-1.7.8-linux-amd64.tar.gz
        dest: /tmp/containerd-1.7.8-linux-amd64.tar.gz

    - name: Extract containerd archive
      become: true
      ansible.builtin.unarchive:
        src: /tmp/containerd-1.7.8-linux-amd64.tar.gz
        dest: /usr/local
        remote_src: true

    - name: Install systemd unit file for containerd
      become: true
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /etc/systemd/system/containerd.service

    - name: Reload systemd
      become: true
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start containerd service
      become: true
      ansible.builtin.service:
        name: containerd
        state: started
        enabled: yes

    - name: Clean up downloaded archive
      become: true
      ansible.builtin.file:
        path: /tmp/containerd-1.7.8-linux-amd64.tar.gz
        state: absent
      register: cleanup_archive

    - name: Show cleanup task result
      ansible.builtin.debug:
        var: cleanup_archive

- name: Install CNI plugins # (required for most pod network)
  hosts: all
  become: true
  vars:
    CNI_PLUGINS_VERSION: 'v1.3.0'
    ARCH: 'amd64'
    CNI_PLUGINS_DEST: '/opt/cni/bin'

  tasks:
    - name: Create /opt/cni/bin directoty if not exists
      file:
        path: "{{ CNI_PLUGINS_DEST }}"
        state: directory

    - name: Download CNI plugins archive
      get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/{{ CNI_PLUGINS_VERSION }}/cni-plugins-linux-{{ ARCH }}-{{ CNI_PLUGINS_VERSION }}.tgz"
        dest: "/tmp/cni-plugins.tgz"

    - name: Extract CNI plugins
      ansible.builtin.unarchive:
        src: "/tmp/cni-plugins.tgz"
        dest: "{{ CNI_PLUGINS_DEST }}"
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Clean up downloaded archive /tmp/cni-plugins.tgz
      become: true
      ansible.builtin.file:
        path: /tmp/cni-plugins.tgz
        state: absent
      register: cleanup_archive